### ISSUE TITLE
frequency for custom MonoTimer

### ISSUE THREAD

**Issue by burrbull** [kalkyl/f411-rtic#1]
https://github.com/kalkyl/f411-rtic/blob/8b0edb7be73d1c1139aed4660a3c30b8b66e084b/src/bin/mono.rs#L19

I think this is incorrect.
Same as

https://github.com/kalkyl/f411-rtic/blob/8b0edb7be73d1c1139aed4660a3c30b8b66e084b/src/bin/rtic-tick.rs#L22

**Comment by burrbull** [comment]
https://github.com/stm32-rs/stm32f4xx-hal/pull/380

**Comment by kalkyl** [comment]
Oups, thanks for the heads up! Should be correct now?

**Comment by burrbull** [comment]
In mono.rs yes, but in example in
```
type MyMono = MonoTimer<pac::TIM2, FREQ>;
```
instead of `FREQ` you should pass value equal or less than `clocks.pclk1().0 * pclk_mul`.
1 MHz good choice for me

**Comment by kalkyl** [comment]
Good idea, changed the example to 1MHz now

**Comment by burrbull** [comment]
Could you test this? I don't have possibility now.

**Comment by kalkyl** [comment]
Yes I already tested it on hardware and all is good 👍
